#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

new_data="/mnt/tank/scratch/yunovikova/masters/new_data"
reference="/mnt/tank/scratch/yunovikova/masters/new_data/reference"

for file in ${new_data}/vcfs_astral/*
do
a="$(cat $file | wc -l)"
  if (( a < 100 ))
  then
  echo $file
  fi
done

ls ${new_data}/vcfs_astral/*.vcf.gz > ${new_data}/files_for_astral/list_of_vcffiles.txt
zgrep "#" ${new_data}/Full_canis_final.recode.vcf.gz > ${new_data}/files_for_astral/header_autosomes.txt
