#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

#-------------------Paths--------------------

masters="/mnt/tank/scratch/yunovikova/masters"
genomes="/mnt/tank/scratch/yunovikova/masters/new_genomes"
fastqc="/mnt/tank/scratch/yunovikova/masters/FastQC_new"

mkdir ${fastqc}/FastQC_before
find ${genomes} -type f -name "*.fastq.gz" | xargs -I {} fastqc {} -t 4 --outdir ${fastqc}/FastQC_before
multiqc -o /mnt/tank/scratch/yunovikova/masters/MultiQC -n multiqc_before ${fastqc}/FastQC_before 
