#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/fastp/fastp_reports

#-------------------Paths--------------------

new_genomes="/mnt/tank/scratch/yunovikova/masters/new_data/new_genomes"
fastp="/mnt/tank/scratch/yunovikova/masters/new_data/fastp"

#-------------------FastP--------------------

for TAG in CLS_1.1 CLS_1.2 CLS_2 CLS_3 LMM_99 UCI_1.1 UCI_1.2 UCI_1.3
do
fastp \
	--in1 ${new_genomes}/${TAG}_1.fastq.gz \
	--out1 ${fastp}/${TAG}_1_fastp.fastq.gz \
	--in2 ${new_genomes}/${TAG}_2.fastq.gz \
	--out2 ${fastp}/${TAG}_2_fastp.fastq.gz \
	--json ${fastp}/fastp_reports/${TAG}.json --html ${fastp}/fastp_reports/${TAG}.html \
	--detect_adapter_for_pe \
	-l 30 \
	-q 20  \
	--overrepresentation_analysis \
	--thread 16 \
	--report_title ${TAG}\
	--trim_poly_g
done
