#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/fastp/fastp_reports
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/FastQC/FastQC_after

#-------------------Paths--------------------

new_genomes="/mnt/tank/scratch/yunovikova/masters/new_data/new_genomes"
fastqc="/mnt/tank/scratch/yunovikova/masters/new_data/FastQC"
fastp="/mnt/tank/scratch/yunovikova/masters/new_data/fastp"

#-------------------FastP--------------------

cd /mnt/tank/scratch/yunovikova/masters/new_data/new_genomes
for file in *_1.fastq.gz
do
fastp \
	--in1 ${new_genomes}/${file} \
	--out1 ${fastp}/${file%%_1.fastq.gz}_1_fastp.fastq.gz \
	--in2 ${new_genomes}/${file%%_1.fastq.gz}_2.fastq.gz \
	--out2 ${fastp}/${file%%_1.fastq.gz}_2_fastp.fastq.gz \
	--json ${fastp}/fastp_reports/${file%%_1.fastq.gz}.json --html ${fastp}/fastp_reports/${file%%_1.fastq.gz}.html \
	--detect_adapter_for_pe \
	-l 30 \
	-q 20  \
	--overrepresentation_analysis \
	--thread 16 \
	--report_title ${file%%_1.fastq.gz}\
	--trim_poly_g
done

#-------------------FastQC--------------------

find ${fastp} -type f -name "*.fastq.gz" | xargs -I {} fastqc {} -t 4 --outdir ${fastqc}/FastQC_after
multiqc -o /mnt/tank/scratch/yunovikova/masters/new_data/MultiQC -n multiqc_after ${fastqc}/FastQC_after
