#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project



#-------------------Paths--------------------

genomes="/mnt/tank/scratch/yunovikova/masters/genomes"
fastqc="/mnt/tank/scratch/yunovikova/masters/FastQC"
fastp="/mnt/tank/scratch/yunovikova/masters/fastp"
reference="/mnt/tank/scratch/yunovikova/masters/reference"
aligned_reads="/mnt/tank/scratch/yunovikova/masters/aligned_reads"
sorted_reads="/mnt/tank/scratch/yunovikova/masters/sorted_reads"

#----------------Index reference--------------

bwa-mem2 index ${reference}/GCF_000002285.5/GCF_000002285.5_Dog10K_Boxer_Tasha_genomic.fna

#-------------------Alignment-----------------

do

bwa-mem2 mem -t 32 -R "@RG\tID:${TAG}\tPL:ILLUMINA\tPU:${TAG}\tLB:${TAG}\tSM:${TAG}" ${reference}/GCF_000002285.5/GCF_000002285.5_Dog10K_Boxer_Tasha_genomic.fna ${fastp}/${TAG}_1_fastp.fastq.gz ${fastp}/${TAG}_2_fastp.fastq.gz \
| samtools view -b > ${aligned_reads}/${TAG}.bam

done

#-------------------Samtools-----------------

for TAG in LMS_NCBI1 LAD_NCBI1 CLU_1 CLU_2 CLU_3 CLU_4 CLU_5 CLU_6 CLU_7 CLU_8 CLS_4 CSI_1 CSI_2 CAU_2 CAU_3 CAU_4 CAL_1 CLA_1 CLA_2 OME_1 CBR_1 CTH_1 LMS_26 LMM_T-2844 LMM_T-3360 LMM_T-3363 CLS_2 CLS_3 LMM_99 CAU_1 LPI_1 LPI_2 UCI_1 CLS_1
do
samtools sort -@ 32 -O bam ${aligned_reads}/${TAG}.bam > ${aligned_reads}/${TAG}.sorted.bam
done

samtools merge -o ${aligned_reads}/UCI_1.sorted.bam ${aligned_reads}/UCI_1.1.sorted.bam ${aligned_reads}/UCI_1.2.sorted.bam ${aligned_reads}/UCI_1.3.sorted.bam
samtools merge -o ${aligned_reads}/CLS_1.sorted.bam ${aligned_reads}/CLS_1.1.sorted.bam ${aligned_reads}/CLS_1.2.sorted.bam

#-------------------MarkDuplicates-----------------

for TAG in LMS_NCBI1 LAD_NCBI1 CLU_1 CLU_2 CLU_3 CLU_4 CLU_5 CLU_6 CLU_7 CLU_8 CLS_4 CSI_1 CSI_2 CAU_2 CAU_3 CAU_4 CAL_1 CLA_1 CLA_2 OME_1 CBR_1 CTH_1 LMS_26 LMM_T-2844 LMM_T-3360 LMM_T-3363 CLS_2 CLS_3 LMM_99 CAU_1 LPI_1 LPI_2 UCI_1 CLS_1
do
gatk MarkDuplicatesSpark --tmp-dir /mnt/tank/scratch/yunovikova/masters/tmp -I ${sorted_reads}/${TAG}.sorted.bam -O ${sorted_reads}/${TAG}.dedup.bam
samtools flagstat ${sorted_reads}/${TAG}.dedup.bam > /mnt/tank/scratch/yunovikova/masters/samtools_reports/${TAG}.dedup.txt
done

multiqc /mnt/tank/scratch/yunovikova/masters/samtools_reports -o /mnt/tank/scratch/yunovikova/masters/MultiQC -n multiqc_samtools
