#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/aligned_reads
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/sorted_reads

#-------------------Paths--------------------

new_genomes="/mnt/tank/scratch/yunovikova/masters/new_data/new_genomes"
fastqc="/mnt/tank/scratch/yunovikova/masters/new_data/FastQC"
fastp="/mnt/tank/scratch/yunovikova/masters/new_data/fastp"
reference="/mnt/tank/scratch/yunovikova/masters/new_data/reference"
aligned_reads="/mnt/tank/scratch/yunovikova/masters/new_data/aligned_reads"
sorted_reads="/mnt/tank/scratch/yunovikova/masters/new_data/sorted_reads"

#----------------Index reference--------------

bwa-mem2 index ${reference}/canFam6.fna

#-------------------Alignment-----------------

cd ${fastp}
for file in *_1_fastp.fastq.gz
do
bwa-mem2 mem -t 32 -R "@RG\tID:${file%%_1_fastp.fastq.gz}\tPL:ILLUMINA\tPU:${file%%_1_fastp.fastq.gz}\tLB:${file%%_1_fastp.fastq.gz}\tSM:${file%%_1_fastp.fastq.gz}" ${reference}/canFam6.fna ${fastp}/${file} ${fastp}/${file%%_1_fastp.fastq.gz}_2_fastp.fastq.gz \
| samtools view -b > ${aligned_reads}/{file%%_1_fastp.fastq.gz}.bam
done

#-----------------Sorting reads----------------

for file in ${aligned_reads}
do
samtools sort -@ 32 -O bam ${file} > ${file%%.bam}.sorted.bam
rm ${file}
done

#-------------------MarkDuplicates-----------------

for TAG in LMS_NCBI1 LAD_NCBI1 CLU_1 CLU_2 CLU_3 CLU_4 CLU_5 CLU_6 CLU_7 CLU_8 CLS_4 CSI_1 CSI_2 CAU_2 CAU_3 CAU_4 CAL_1 CLA_1 CLA_2 OME_1 CBR_1 CTH_1 LMS_26 LMM_T-2844 LMM_T-3360 LMM_T-3363 CLS_2 CLS_3 LMM_99 CAU_1 LPI_1 LPI_2 UCI_1 CLS_1
do
gatk MarkDuplicatesSpark --tmp-dir /mnt/tank/scratch/yunovikova/masters/tmp -I ${sorted_reads}/${TAG}.sorted.bam -O ${sorted_reads}/${TAG}.dedup.bam
samtools flagstat ${sorted_reads}/${TAG}.dedup.bam > /mnt/tank/scratch/yunovikova/masters/samtools_reports/${TAG}.dedup.txt
done

multiqc /mnt/tank/scratch/yunovikova/masters/samtools_reports -o /mnt/tank/scratch/yunovikova/masters/MultiQC -n multiqc_samtools
