#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/aligned_reads
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/dedup_reads
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/samtools_reports
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/Metrics/MarkDulicates
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/Metrics/CollectWgsMetrics
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/Metrics/CollectAlignmentSummaryMetrics
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/Metrics/Mosdepth
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/Metrics/Samtools_reports

#-------------------Paths--------------------

new_genomes="/mnt/tank/scratch/yunovikova/masters/new_data/new_genomes"
fastqc="/mnt/tank/scratch/yunovikova/masters/new_data/FastQC"
fastp="/mnt/tank/scratch/yunovikova/masters/new_data/fastp"
reference="/mnt/tank/scratch/yunovikova/masters/new_data/reference"
aligned_reads="/mnt/tank/scratch/yunovikova/masters/new_data/aligned_reads"
dedup_reads="/mnt/tank/scratch/yunovikova/masters/new_data/dedup_reads"
Metrics="/mnt/tank/scratch/yunovikova/masters/new_data/Metrics"

#----------------Index reference--------------

bwa-mem2 index ${reference}/canFam6.fna

#-------------------Alignment-----------------

cd ${fastp}
for file in *_1_fastp.fastq.gz
do
bwa-mem2 mem -t 32 -R "@RG\tID:${file%%_1_fastp.fastq.gz}\tPL:ILLUMINA\tPU:${file%%_1_fastp.fastq.gz}\tLB:${file%%_1_fastp.fastq.gz}\tSM:${file%%_1_fastp.fastq.gz}" ${reference}/canFam6.fna ${fastp}/${file} ${fastp}/${file%%_1_fastp.fastq.gz}_2_fastp.fastq.gz \
| samtools view -b > ${aligned_reads}/${file%%_1_fastp.fastq.gz}.bam
done

#-------Sorting reads and MarkDuplicates------

cd ${aligned_reads}
for file in *
do
samtools sort -@ 32 -O bam ${file} > ${dedup_reads}/${file%%.bam}.sorted.bam
java -jar /mnt/tank/scratch/yunovikova/picard/picard.jar MarkDuplicates \
    --TMP_DIR /mnt/tank/scratch/yunovikova/masters/tmp \
    -I ${dedup_reads}/${file%%.bam}.sorted.bam \
    -M ${dedup_reads}/${file%%.bam}.metrics.txt \
    -O ${dedup_reads}/${file%%.bam}.dedup.bam
samtools flagstat ${dedup_reads}/${file%%.bam}.dedup.bam > /mnt/tank/scratch/yunovikova/masters/new_data/samtools_reports/${file%%.bam}.dedup.txt
done

#------------Flagstat multiqc-----------------

multiqc /mnt/tank/scratch/yunovikova/masters/new_data/samtools_reports -o /mnt/tank/scratch/yunovikova/masters/new_data/MultiQC -n multiqc_samtools
