#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/FastQC/FastQC_before
mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/MultiQC

#-------------------Paths--------------------

new_genomes="/mnt/tank/scratch/yunovikova/masters/new_data/new_genomes"
fastqc="/mnt/tank/scratch/yunovikova/masters/new_data/FastQC"

#-------------------FastQC--------------------

find ${new_genomes} -type f -name "*.fastq.gz" | xargs -I {} fastqc {} -t 4 --outdir ${fastqc}/FastQC_before
multiqc -o /mnt/tank/scratch/yunovikova/masters/new_data/MultiQC -n multiqc_before ${fastqc}/FastQC_before 
