#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

mkdir -p /mnt/tank/scratch/yunovikova/masters/new_data/HaplotypeCaller

#-------------------Paths--------------------

reference="/mnt/tank/scratch/yunovikova/masters/new_data/reference"
dedup_reads="/mnt/tank/scratch/yunovikova/masters/new_data/dedup_reads"
HaplotypeCaller="/mnt/tank/scratch/yunovikova/masters/new_data/HaplotypeCaller"

#--------------HapplotypeCaller--------------

gatk CreateSequenceDictionary -R ${reference}/canFam6.fna
samtools faidx ${reference}/canFam6.fna

cd ${dedup_reads}
for file in *
do
mkdir -p ${HaplotypeCaller}/${file%%.dedup.bam}
samtools index $file
done
