#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

#-------------------Paths--------------------

new_genomes="/mnt/tank/scratch/yunovikova/masters/new_data/new_genomes"
fastqc="/mnt/tank/scratch/yunovikova/masters/new_data/FastQC"
fastp="/mnt/tank/scratch/yunovikova/masters/new_data/fastp"
reference="/mnt/tank/scratch/yunovikova/masters/new_data/reference"
aligned_reads="/mnt/tank/scratch/yunovikova/masters/new_data/aligned_reads"
dedup_reads="/mnt/tank/scratch/yunovikova/masters/new_data/dedup_reads"
Metrics="/mnt/tank/scratch/yunovikova/masters/new_data/Metrics"


#-------------SummaryMetrics-----------------

cd ${dedup_reads}
for file in *
do
samtools flagstat $file > ${Metrics}/Samtools_reports/${file%%.bam}.txt
java -jar /mnt/tank/scratch/yunovikova/picard/picard.jar CollectWgsMetrics -I $file -O ${Metrics}/CollectWgsMetrics/${file%%.bam}.wgs_metrics.txt -R ${reference}/canFam6.fna
java -jar /mnt/tank/scratch/yunovikova/picard/picard.jar CollectAlignmentSummaryMetrics -I $file -O ${Metrics}/CollectAlignmentSummaryMetrics/${file%%.bam}.alignment_metrics.txt -R ${reference}/canFam6.fna
mosdepth -t 16 -n --fast-mode ${Metrics}/Mosdepth/${file%%.bam} $file
done

#------------Metrics multiqc-----------------

multiqc /mnt/tank/scratch/yunovikova/masters/new_data/Metrics -o /mnt/tank/scratch/yunovikova/masters/new_data/MultiQC -n multiqc_Metrics
