#!/bin/bash -i
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8G
#SBATCH --array=1-38%8

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

#-------------------Paths--------------------

reference="/mnt/tank/scratch/yunovikova/masters/new_data/reference"
new_data="/mnt/tank/scratch/yunovikova/masters/new_data"

mkdir -p ${new_data}/GenotypeGVCFs

gatk --java-options "-Xmx8G -XX:ParallelGCThreads=4 -Djava.io.tmpdir=/mnt/tank/scratch/yunovikova/masters/tmp" GenotypeGVCFs \
   -R ${reference}/canFam6.fna \
   -V ${new_data}/CombineGVCFs/VCF_${SLURM_ARRAY_TASK_ID}.g.vcf.gz \
   -O ${new_data}/GenotypeGVCFs/canis_${SLURM_ARRAY_TASK_ID}.vcf.gz
