#!/bin/bash -i

/nfs/home/yunovikova/.local/bin/micromamba shell init -s bash -p ~/micromamba
source ~/.bashrc
micromamba activate project

#-------------------Paths--------------------

new_data="/mnt/tank/scratch/yunovikova/masters/new_data"
reference="/mnt/tank/scratch/yunovikova/masters/new_data/reference"

gatk SelectVariants \
    -V ${new_data}/Full_canis_autosomes.vcf.gz \
    -select-type SNP \
    -O ${new_data}/Full_canis_snps.vcf.gz

gatk VariantFiltration \
    -V ${new_data}/Full_canis_snps.vcf.gz \
    --filter-name "QD2" --filter-expression "QD < 2.0" \
    --filter-name "QUAL30" --filter-expression "QUAL < 30.0" \
    --filter-name "SOR3" --filter-expression "SOR > 3.0" \
    --filter-name "FS60" --filter-expression "FS > 60.0" \
    --filter-name "MQ40" --filter-expression "MQ < 40.0" \
    --filter-name "MQRankSum-12.5" --filter-expression "MQRankSum < -12.5" \
    --filter-name "ReadPosRankSum-8" --filter-expression "ReadPosRankSum < -8.0" \
    -O ${new_data}/Full_canis_snps_hard_filtered.vcf.gz

bcftools view -f .,PASS -o ${new_data}/Full_canis_snps_hard_filtered_pass.vcf.gz ${new_data}/Full_canis_snps_hard_filtered.vcf.gz

bcftools filter -e 'FMT/DP<10 || FMT/GQ<20' -o ${new_data}/Full_canis_snps_hard_filtered_pass_DP_GQ.vcf.gz ${new_data}/Full_canis_snps_hard_filtered_pass.vcf.gz

vcftools --gzvcf ${new_data}/Full_canis_snps_hard_filtered_pass_DP_GQ.vcf.gz \
  --remove-indels \
  --min-alleles 2 \
  --max-alleles 2 \
  --non-ref-ac-any 1 \
  --out ${new_data}/Full_canis_snps_hard_filtered_pass_DP_GQ_biallelic

bgzip ${new_data}/Full_canis_snps_hard_filtered_pass_DP_GQ_biallelic.vcf

bcftools view -e 'FMT/AD[:1] < 5 & FORMAT/GT="alt"' -o ${new_data}/Full_canis_snps_hard_filtered_pass_DP_GQ.vcf.gz ${new_data}/Full_canis_snps_hard_filtered_pass_DP_GQ_biallelic.vcf.gz

vcftools --gzvcf ${new_data}/Full_canis_snps_hard_filtered_pass_DP_GQ_biallelic.vcf.gz \
  --max-missing 0.9 \
  --out ${new_data}/Full_canis_final

vcftools --gzvcf ${new_data}/Full_canis_snps_pass.vcf.gz --keep Lupulella.txt \
  --max-missing 0.9 \
  --out ${new_data}/Lupulella

vcftools --gzvcf ${new_data}/Full_canis_snps_pass.vcf.gz --keep Lupulella_with_CTH.txt \
  --max-missing 0.9 \
  --out ${new_data}/Lupulella_with_CTH

vcftools --gzvcf ${new_data}/All_vcf/Full_canis_snps_pass.vcf.gz --keep ${new_data}/All_vcf/LMS_dhole.txt \
  --max-missing 0.9 \
  --out ${new_data}/All_vcf/LMS_dhole
  
vcftools --gzvcf ${new_data}/All_vcf/Full_canis_snps_pass.vcf.gz --keep ${new_data}/All_vcf/LMS_ahd.txt \
  --max-missing 0.9 \
  --out ${new_data}/All_vcf/LMS_ahd

bgzip ${new_data}/Full_canis_final.vcf
bgzip ${new_data}/Lupulella.vcf
bgzip ${new_data}/Lupulella_with_CTH.vcf
bgzip ${new_data}/LMS_dhole.vcf
bgzip ${new_data}/LMS_ahd.vcf
